spring:
  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
  redis:
    database: 0
    host: loaclhost
    port: 6379
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl