spring:
  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
  redis:
    database: 0
    host: localhost
    port: 6379
  cache:
    type: caffeine
    cache-names: teacher
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s
  zipkin:
    enabled: true
    base-url: http://localhost:9411/
  sleuth:
    enabled: true
    sampler:
      # 采样率
      probability: 1
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss}] [${PID:- }] %clr([%p]) [${spring.application.name},%X{X-B3-TraceId:-},%X{X-B3-ParentSpanId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}] [%thread] [%class:%line] %clr([%m]) [%wEx]%n"