spring:
  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
  redis:
    database: 0
    host: loaclhost
    port: 6379
  cache:
    type: caffeine
    cache-names: teacher
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

hystrix:
  command:
    # 有的属性时默认值，写不写都行
    default:
      fallback:
        enabled: true
      circuitBreaker:
        enabled: true
        # 超过 50% 的错误，那么开启熔断
        errorThresholdPercentage: 50
        # 5 个 request 之后才进行统计
        requestVolumeThreshold: 5
        # 10 秒之后进入半开状态
        sleepWindowInMilliseconds: 10000
        # forceOpen，forceClosed 强制开启/关闭熔断开关
      execution:
        timeout:
          enabled: true
        # 可以指定隔离方式：线程池 or 信号量
        isolation:
          thread:
            interruptOnTimeout: true
            interruptOnFutureCancel: true
            timeoutInMilliseconds: 10000
        metrics:
          rollingStats:
            # 时间窗口统计
            timeInMilliseconds: 20000
#            numBuckets: 10
#          rollingPercentile:
#            # 时间窗口统计
#            timeInMilliseconds: 20000
#            bucketSize: 100